# Peer Production Experience Report: Namuwiki 

Joohee Oh
_Citations use APA format_

## Introduction
I participated in the work of a peer-production community called Namuwiki, the most popular wiki in South Korea. By editing one of its topics, I expect to understand the process of contributing to this community and how my contribution is recognized and verified based on Namuwiki's policy. I will also compare its policy with Wikipedia, especially in terms of the neutral point of view policy. 

## The process and motivation compared with expectations
First, I made my account and logged in as it is necessary to edit any topic. I tried to choose one of the recent popular items, but they were unexpectedly not familiar with me. Therefore, I searched the "Austin" document, which seemed to be written by users who have lived in Austin, describing this city with positive (not strictly neutral) feelings with a somewhat informal tone. To illustrate, when explaining the unofficial slogan "Keep Austin Weird," a user also added, "Austin is open-minded towards the new culture and new people. It makes Austin weird in a good way." Although many people would agree with it (as Austin often ranks the best place to live in the USA), the experiences in Austin could be different among people.

I clicked the editing button and started to make my contribution. I separated the previous page written in one paragraph into several paragraphs and rearranged them into subcategories, including demographics, industry, culture, etc. Since I got more engaged when I saw this page well-organized after rearrangement, I wanted to create more contributions. My motivation was “fun” among the eight motivational categories identified by Nov. I wrote additional information about Austin's food industry, mentioning Austin has the headquarters of Whole Foods and famous barbecue places. I saved the page, and it was uploaded on the newly edited document list. This participation was recorded as my first contribution to Namuwiki. 

A couple of days later, a user reviewed this document and added Tex-Mex cuisines in the food category. The user also mentioned the slogan was created by Karen Pavelka, one of our faculties at the iSchool, and her husband, who were worried about Austin's over-development. The user also agreed Austin looks positively weird, but not every Austinite are open-minded but rather conservative, guessing it is originated from Austin's location and history. I was glad to see my work was reviewed, new facts were, and learn the origin of the slogan. I felt like I would continue editing other documents as long as I could enjoy editing and learn from it. It was intrinsic motivation described by Crowston and Howison, enjoyment-based motivations such as fun and learning opportunities. Crowston and Fagnot stated three stages of contribution as initial, sustained, and meta contribution. The critical factors for the sustained contribution are the contributor's feelings of obligation to the project, the intrinsic motivation of the task, and feedback from the task and other participants. To encourage more feedback from participants, Namuwiki shows the list of recently updated documents on the front page, and it has special menus where controversial topics are discussed, or unclassified/short/edition-is-needed topics are collected.

## What is similar or different from Wikipedia?
I searched “Austin” from Wikipedia, where Austin's history, geopolitical characteristics, climate, environment, traffic, and politics are objectively described in separate paragraphs. It was expected given that Wikipedia was created based on the model of the encyclopedia, and has a neutral point of view policy dealing with how to maintain neutrality according to Butler. Namuwiki, however, started from a community that used to share information and evaluation for subcultural artifacts. This origin has led to creating Namuwiki's unique features, such as sharing detailed information about particular topics and allowing different points of view, stating clearly, “Namuwiki is a wiki and not an encyclopedia. It may contain unverified, biased, or misleading statements.” 

## Conclusion
The participation process was interesting enough to keep me motivated as I expected, while Namuwiki’s efforts to create more participation exceeded my expectations. It was impressive that Namuwiki states its unique identity as a wiki, not an encyclopedia which requires a neutral point of view or sources for description. Namuwiki is meaningful in that it provides reasonable witty information about various topics and different insights on them.


## References
-	[Namuwiki] (https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8)
-	Nov, O. (2007). What motivates Wikipedians? Communications of the ACM, 50(11), 60–64. doi: 10.1145/1297797.1297798
-	Crowston, K., & Fagnot, I. (2018). Stages of motivation for contributing user-generated content: A theory and empirical test. International Journal of Human-Computer Studies, 109, 89–101. doi: 10.1016/j.ijhcs.2017.08.005
-	Crowston, K., Wei, K., Howison, J., & Wiggins, A. (2012). Free/Libre open-source software development. ACM Computing Surveys, 44(2), 1–35. doi: 10.1145/2089125.2089127
-	Butler, B., Joyce, E., & Pike, J. (2008). Dont look now, but weve created a bureaucracy. Proceeding of the Twenty-Sixth Annual CHI Conference on Human Factors in Computing Systems - CHI 08. doi: 10.1145/1357054.1357227

