---
title: "R Notebook"
output: html_notebook
---

# Allow on-going development in master and branch

This extends the exercise to a situation in which the repository owner has also been working while the collaborators are making their edits.  The repository owner will be working in a branch, then when they are ready they will synchronize with the work the collaborators have been doing, and then add their work on that newly synchronzied base.  

1. *Contributor A* should pick (or create) a repository on github as the shared/upstream repository, and work with an up to date clone. Create, add, commit, and push a file called `animals.txt` with this content:
```
lion
tiger
leopard
turtle
```
2. *Maintainer* and *Contributor B* should make forks of the shared repository on github, and create clones of their forks. They should set the shared repository as upstream.

<div class="spoiler">
```sh
$ git clone <fork_repo_url>
$ git remote add upstream <shared_repo_url>
```
</div>

3. *Maintainer* is working with a direct link to the shared repository, so they should preserve `master` as a place to gather contributions. That means to work on their own they should always use a branch. *Maintainer* should create a branch on their local repo.

<div class="spoiler">
```sh
$ git checkout -b my_color_branch
```
</div>

4. *Maintainer* should edit the `animals.txt` file to add a different color alongside `lion` (e.g., `lion purple`). Add and commit this edit to the new branch.

5. *Contributor A* and *Contributor B* should each edit the file by adding a different color to the first line in the `animals.txt` (so it reads `lion red` or `lion green`). They add, commit, push to their forks.

6. *Maintainer* and *Contributor B* should then go to github and look at their forks.  They should create a pull request by hitting the 'New Pull Request' button. 

7. With everyone looking at *Contributor A*'s computer, *Contributor A* should refresh the github page for the shared repository and will see two pull-requests in the pull-request tab. Accept each one, resolving any conflicts that emerge. They can choose whatever contributions they want (the original line, the line with the color from *Contributor B* or the line with the color from *Contributor A*); however the file is after removing the `<<<<<` `========` and `>>>>>>` lines will be what is in the shared repository.

8. *Contributor A* now needs to synchronize with the work the collaborators have done since *Contributor A* started the `my_color_branch` branch.  *Contributor A* should ensure their changes are committed to the branch, then switch to master and pull the community's changes.  Then merge their work from `my_color_branch` and resolve any conflicts and complete the merge.

<div class="spoiler">
```sh
$ git branch
$ git status
$ git checkout master
$ git pull
$ git merge my_color_branch
$ git add animals.txt
$ git commit -m "ensured my changes were synchronized with work from community"
```
</div>

9. *Contributor A* now has the latest, synchronized, version of the combined work in the master branch on their local repo.  That should be shared by pushing up to the shared repo.

<div class="spoiler">
```sh
$ git push
```
</div>


10. *Maintainer* and *Contributor B* should then obtain those changes by pulling upstream, then pushing to their forks.

<div class="spoiler">
```sh
$ git pull upstream master
$ git push
```
</div>

11. Finally *Contributor A* should delete the now no longer used branch, which is only in their local repo.

<div class="spoiler">
```sh
$ git branch -d my_color_branch
```
</div>

Phew!


